### ISSUE TITLE
Issue with UTF8 charset

### ISSUE THREAD

**Issue by zamarrong** [jacquestvanzuydam/laravel-firebird#16]
Always whem im trying to get UTF8 characters like ñ, á, ó, é, ° etc i have this error, help me please i need fix this to have mi app in production.

UnexpectedValueException in Response.php line 403:
The Response content must be a string or object implementing __toString(), "boolean" given.

**Comment by jacquestvanzuydam** [comment]
Have you explicitly set the UTF8 charset in your .etc file?
A snippet of your code would also be helpful.

**Comment by Hesto** [comment]
Hello,
I have the same problem. My database has charset =WIN1250 . I set it in .env file and still i can't get characters like ą,ł,ę,ó,ć etc. Do you have any solution?

**Comment by zamarrong** [comment]
Hello, i solved it putting this function on my models:

public function setRawAttributes(array $attributes, $sync = false)
    {
        foreach ($attributes as $index => $attribute)
        {
                $attributes[$index] = utf8_decode($attribute);
        }
        return parent::setRawAttributes($attributes, $sync);
    }
