### ISSUE TITLE
PDOException in Connector.php line 55: could not find driver

### ISSUE THREAD

**Issue by pfloriginale** [jacquestvanzuydam/laravel-firebird#18]
Detail
1. in Connector.php line 55
2. at PDO->__construct('firebird:dbname=localhost:/storage/firebird/name_database.FDB', 'sysdba', 'masterkey', array('0', '2', '0', false, false)) in Connector.php line 55

Somebody could help me?
### I coded

> composer require jacquestvanzuydam/laravel-firebird:dev-5.1-support

added to config/database.php 

```
    'firebird' => [
        'driver'   => 'firebird',
        'host'     => env('DB_HOST', 'localhost'),
        'database' => '/storage/firebird/G_CHIOSCO.FDB',
        'username' => 'sysdba',
        'password' => 'masterkey',
        'charset'  => env('UTF8'),
    ],
```

added to config/app.php

> Firebird\FirebirdServiceProvider::class,

added

> DB_CHARSET=UTF8

I use in the same project also a mysql database, so in the model where i need this connection i coded

added to the stats.php model

> protected $connection = 'firebird';

Thanks a lot look like great job and i would like try!

**Comment by cedamorim** [comment]
Change this line 'charset'  => env('UTF8')  to 'charset'  => env('DB_CHARSET', 'UTF8'),

**Comment by jacquestvanzuydam** [comment]
If you still having problems after using the suggestion that @cedamorim suggested, please let us know?

**Comment by pfloriginale** [comment]
Change but... no fixed

2016-01-19 14:48 GMT+01:00 Jacques van Zuydam notifications@github.com:

**Comment by jacquestvanzuydam** [comment]
If I understand you correctly, you are trying to use both mysql and firebird?

Have you tried removing/commenting out the `Illuminate\Database\DatabaseServiceProvider::class,` in app.php?

As the Firebird driver does extend the original service provider.

**Comment by cedamorim** [comment]
Wow, sorry .. I did not pay attention right in the title, apparently you forgot to enable the extension of the firebird for pdo http://php.net/manual/en/ref.pdo-firebird.php

**Comment by pfloriginale** [comment]
Thanks guys for attention but are a lot of day I try without result...

I'm testing on XAMP with Windows 64 bit
- I have download and installer from site firebird 2.5
- I uncommented from php.in "extension=php_pdo_firebird.dll"

But..

php give me always this error
PHP Warning:  PHP Startup: Unable to load dynamic library 'E:\Programmi\xamp\php\ext\php_pdo_firebird.dll' - %1 non è un'applicazione di Win32 valida.

In italian means "php_pdo_firebird.dll is not a valid win 32 application"

I can't find solution and I would like to try this!

**Comment by jacquestvanzuydam** [comment]
Paolo, unfortunately I don't use Windows to develop with. Perhaps someone else using this library can help with the installation of the PDO for windows?

What I can suggest however is using a Vagrant Box like the homestead one used for testing/developing in Laravel and install Firebird on it.

Please look at the following links for more about Vagrant and Homestead:

https://www.vagrantup.com

https://laravel.com/docs/5.2/homestead

**Comment by cristiano-pacheco** [comment]
hello paulo,
you need to enable the extension pdo firebird in php.ini.
for this, search for ;extension=pdo_firebird in your php.ini and remove; at the beginning of the line.
restart your apache and'll be resolved.

**Comment by pfloriginale** [comment]
Thanks a lot... but the problem maybe is other...

my php.ini is..

```
...
;extension=php_openssl.dll
extension=php_pdo_firebird.dll
;extension=php_pdo_mysql.dll
...
```

But it give me this error on the shell if i test "php"

> PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/bitnami/php/lib/php/extensions/php_pdo_firebird.dll' - /opt/bitnami/php/lib/php/extensions/php_pdo_firebird.dll: cannot open shared object file: No such file or directory in Unknown on line 0

Now i'm testing on AMAZON AWS 
bitnami
-lampstack-5.5.29-1
-linux-ubuntu-14.04.1-x86_64

**Comment by pfloriginale** [comment]
Another thigs is that php looking for a php_pdo_fiebird.dll in this folder, where, there are oly *.so files.

Is correct?
Sorry... I'm a really newbie about server config

![cattura](https://cloud.githubusercontent.com/assets/16399563/12887383/1a3fef5a-ce74-11e5-8fe5-c4d092d8a2a8.PNG)

**Comment by pfloriginale** [comment]
FIXED!

in php.ini I changed

from
`extension=php_pdo_firebird.dll`
to
`extension=pdo_firebird.so`

Really I don't know because but it works! 
I promise i will study apache and php enviroment!
:)

look like great... now I try :)))

**Comment by pfloriginale** [comment]
FIXED also in local with XAMP

I work with windows 7 64 bit, but XAMP want a fbclient.dll 32 bit

So... i download from firebird site a .zip 32 bit version for windows, take only che fbclient.dll and put in the root php...

**Comment by jacquestvanzuydam** [comment]
I am glad to hear you managed to solve this. I'd still recommend using a modified Vagrant Laravel Homestead over XAMP.

**Comment by bhrandon** [comment]
Good afternoon, I'm brazilian and I'm having an error when doing the migration for firebird, I have all the firebird drives in wamp64 started and I'm using laravel 5.3 with its 5.3 package as well.

![erroexeptionpdodriver](https://cloud.githubusercontent.com/assets/20459863/20937999/656fabba-bbd0-11e6-8cf5-7c5d481e59e6.png)

**Comment by jacquestvanzuydam** [comment]
Hi @bhrandon ,
Have you followed the steps used by @pfloriginale ?

I don't have a Windows environment to test / replicate this with, but it looks like a firebird isn't installed correctly.

**Comment by pfloriginale** [comment]
If you don t want lose too much time in fixing... Use vagrant+homestead.


I use this pack from 1 yr and its great

**Comment by bhrandon** [comment]
Good morning, I've followed every step. I want to ask you a favor @pfloriginale, could you create a tutorial on how to use the package with firebird on windows? I think this is going to help a lot of people. And only you can help me.

**Comment by pfloriginale** [comment]
May I know why you don't use vagrant + homestead?
Need a little bit of time to learn it, but it solves also your future issues.

**Comment by ahmed-bermawy** [comment]
You need to install php module for **pdo_mysql**

to do that run this command on your server

`yum install php-mysqlnd`

Then restart httpd service

`service httpd restart`
