### ISSUE TITLE
5.2.x Compatibility

### ISSUE THREAD

**Issue by sistemasjg** [jacquestvanzuydam/laravel-firebird#19]
Is there any compatibility issue with Laravel 5.2.x that can cause malfunction with your package? I've been trying to install on it, but keeps me showing errors about laravel version.

Thanks in advance,

**Comment by jacquestvanzuydam** [comment]
I haven't done any testing or development in 5.2 yet, as I have other non-laravel projects taking up my time.
You should be able to pull the source and adjust the `composer.json` file to allow for 5.2.
If you wish to do so and test it and create a fork for 5.2. I will gladly merge a 5.2.\* branch back into this repository.
