### ISSUE TITLE
Erro driver does not support lastInsertId()

### ISSUE THREAD

**Issue by alexrodcruz** [jacquestvanzuydam/laravel-firebird#25]
you can help me?

PDOException in Processor.php line 34:
SQLSTATE[IM001]: Driver does not support this function: driver does not support lastInsertId()

**Comment by cristiano-pacheco** [comment]
in your model, sets the $incrementing attribute with value false.

public $incrementing = false;

**Comment by jacquestvanzuydam** [comment]
Please look at this [issue](https://github.com/jacquestvanzuydam/laravel-firebird/issues/12) regarding the implementation using generators for auto-increment, as you should know that Firebird does not support auto-increment, which is unfortunately the underlying reason why the driver does not support lastinsertid()... I haven't had a chance to implement a work around yet, as I want to automate the insertion of generator tables within migrations, but haven't had stable results yet.

**Comment by alexrodcruz** [comment]
It worked! Thank you!!

**Comment by sheengKwayla** [comment]
Good day, may i know in what model did you put the public $incrementing = false; ?
@alexrodcruz

**Comment by JoaoOliveiracc** [comment]
@cristiano-pacheco in which model should I declare public $ incrementing = false?
