### ISSUE TITLE
Can't query stored procedures

### ISSUE THREAD

**Issue by victorvilella** [jacquestvanzuydam/laravel-firebird#27]
Hi Guys.

I'm working on an API which uses FB 1.5 database. For my surprise, this drivers works in a old version firebird database.

However I cant query stored procedure due a quotation marks on table name.

**Laravel query**
`select * from "E_SP_PLANILHA_VENDA_LOJAS('', '', '', '')" order by "CODIGO_LOJA"`

**Supposed correct query**
`select * from E_SP_PLANILHA_VENDA_LOJAS('', '', '', '') order by "CODIGO_LOJA"`

If has a way to force this driver to dont placle quotation marks? If dont, may I make a PR to add this functionality?

Thanks.

**Comment by cedamorim** [comment]
How are you generating your SQL? Have you tried it?

```
DB::select('select * from E_SP_PLANILHA_VENDA_LOJAS('', '', '', '') order by "CODIGO_LOJA"')
```

Obs: Sou BR tb, ainda não tentei usar procedures com o laravel, mas acho que você pode tentar fazer pelo q te passei acima, qq coisa da um toque ae

**Comment by victorvilella** [comment]
Yep. I'm using raw query feature to overpass this little problem. This weekend I'll work on this feature to avoid project problems.

Thanks anyway.
