### ISSUE TITLE
dev-5.3-support fail

### ISSUE THREAD

**Issue by jerasa** [jacquestvanzuydam/laravel-firebird#31]
composer require jacquestvanzuydam/laravel-firebird:dev-5.3-support fails on illuminate/events.
Maybe you have to update composer.json to include 5.3.\* of Illuminate libraries instead of 5.0.*

**Comment by jacquestvanzuydam** [comment]
Have updated the composer.json file as per your request. Was awaiting feedback from another user to test the package.
