### ISSUE TITLE
Problem in Laravel 5.3

### ISSUE THREAD

**Issue by eliasaparecido** [jacquestvanzuydam/laravel-firebird#34]
ErrorException in ConnectionFactory.php line 21:
Declaration of Firebird\ConnectionFactory::createConnection() should be compatible with Illuminate\Database\Connectors\ConnectionFactory::createConnection($driver, $connection, $database, $prefix = '', array $config = Array)

What can it be?

**Comment by jacquestvanzuydam** [comment]
[clezioalves](https://github.com/clezioalves) made a pull request that I just merged that will possibly fix this.
