### ISSUE TITLE
Missing charset definition in DSN

### ISSUE THREAD

**Issue by risperdal** [jacquestvanzuydam/laravel-firebird#35]
https://github.com/jacquestvanzuydam/laravel-firebird/blob/fda5fed6d2841014ec80fc99682d50884cd44aa3/src/Firebird/FirebirdConnector.php#L29

``` php
return $this->createConnection("firebird:dbname={$host}:{$path}", $config, $options);
```

**Comment by jacquestvanzuydam** [comment]
Please pull latest commit.
