### ISSUE TITLE
Eloquent outside

### ISSUE THREAD

**Issue by whera** [jacquestvanzuydam/laravel-firebird#38]
I'm using Eloquent in a project outside of Laravel, I wonder how I register your provider to use adapter?

**Comment by jacquestvanzuydam** [comment]
It may be possible if you install the illuminate dependencies that this project extends.

**Comment by whera** [comment]
The dependencies have been installed, because I do not know how to add the adapter, because my project does not exist the app / config / app.php.
I would like to know which chasse to call to add the adapter.

**Comment by jacquestvanzuydam** [comment]
Did you read the documentation on [illuminate/database](https://packagist.org/packages/illuminate/database)

The example there should be able to help you.
