### ISSUE TITLE
Laravel 5.4 Support

### ISSUE THREAD

**Issue by josuecorm** [jacquestvanzuydam/laravel-firebird#40]
Hi.

I've upgrade Laravel to 5.4 but now I have problems with laravel-firebird. Will there be support for this version?

**Comment by victorvilella** [comment]
Can you provide a error log? Maybe we (you, me, and others) can help this project to give support to 5.4.

**Comment by jacquestvanzuydam** [comment]
You should be able to change the version of Laravel to `5.4.*` in the `composer.json` file after pulling the [Laravel 5.3 branch](https://github.com/jacquestvanzuydam/laravel-firebird/tree/5.3-support). I haven't created a branch yet not sure what is the best way to version this alongside Laravel. Any ideas would be appreciated.

**Comment by jacquestvanzuydam** [comment]
Have made the following branch for [5.4 support](https://github.com/jacquestvanzuydam/laravel-firebird/blob/5.4-support/composer.jsonl)
