### ISSUE TITLE
Laravel 5.4 Support

### ISSUE THREAD

**Issue by ivanjpolanco** [jacquestvanzuydam/laravel-firebird#41]
Hello,

Thanks for this package. 

Installing it via Composer prints this error.

  Problem 1
    - Installation request for jacquestvanzuydam/laravel-firebird dev-5.3-support -> satisfiable by jacquestvanzuydam/la
ravel-firebird[dev-5.3-support].
    - Conclusion: remove laravel/framework v5.4.6
    - Conclusion: don't install laravel/framework v5.4.6
    - jacquestvanzuydam/laravel-firebird dev-5.3-support requires illuminate/events 5.3.* -> satisfiable by illuminate/e
vents[v5.3.0, v5.3.16, v5.3.23, v5.3.4].
    - don't install illuminate/events v5.3.0|don't install laravel/framework v5.4.6
    - don't install illuminate/events v5.3.16|don't install laravel/framework v5.4.6
    - don't install illuminate/events v5.3.23|don't install laravel/framework v5.4.6
    - don't install illuminate/events v5.3.4|don't install laravel/framework v5.4.6
    - Installation request for laravel/framework (locked at v5.4.6, required as 5.4.*) -> satisfiable by laravel/framework[v5.4.6].

Will we be having support for Laravel 5.4.*?

Can i install it manually? Do i need to modify any files to make it work with Laravel 5.4.

Thanks.

**Comment by df-arif** [comment]
+1

**Comment by jacquestvanzuydam** [comment]
Hi please pull this branch [5.4-support](https://github.com/jacquestvanzuydam/laravel-firebird/blob/5.4-support/composer.json)

**Comment by ivanjpolanco** [comment]
Thank you!
