### ISSUE TITLE
No treatment for string on insert

### ISSUE THREAD

**Issue by ShellOliver** [jacquestvanzuydam/laravel-firebird#45]
When try insert using create or DB:insert(), the string values is not with double quotes.

> QueryException in Connection.php line 662:
> SQLSTATE[HY000]: General error: -204 Dynamic SQL Error SQL error code = -204 Table unknown USERS At line 1, column 13 (SQL: insert into users (name, email, password) values (teste, teste@teste.com, asdasd))

php7, firebird 2.5.7, laravel 5.1

**Comment by KKSzymanowski** [comment]
Are you sure you have the USERS table?
I think there are never quotes in Exception messages in Laravel, but more importantly Firebird would throw a syntax error if something was wrong with the quotes, before even considering checking for table existence.

**Comment by ShellOliver** [comment]
It works if I use PDO directly, using the same connection configured on laravel using:
$pdo = DB::connection()->getPdo();
But I would like do it using create or DB:insert() function.
