### ISSUE TITLE
Help = Creating registers with blob field 

### ISSUE THREAD

**Issue by gustavodebiasi** [jacquestvanzuydam/laravel-firebird#48]
I'm having a problem when using Eloquent with blob fields... The execution stops...
What can I do?

Thanks

**Comment by gustavodebiasi** [comment]
I'm using like the code above:

$data = [
            'COD_PRD' => 87,
            'COD_GRUPO' => 5,
            'COD_UN' => 9,
            'COD_CF' => 26,
            'COD_ALT' => 'TESTEPORD74',
            'DESCR' => 'TESTE DE PRODUTO WEB POR ELOQUENT',
            'COD_ORIGEM' => 0,
            'QTDE_VOL' => 0,
            'VLR_VENDA' => 13.65,
            'STATUS' => 0,
            'COD_FILIAL' => 1,
            'COD_TIPO' => 0,
        ];

        $produto = Produto::create($data);
        $produto->OBS = mb_convert_encoding('AAAAAA','Windows-1252');
        $produto->save();

When I put the part of OBS, the execution stops.

**Comment by KKSzymanowski** [comment]
I think there's a similar issue #47. @douglasmsantos, did you solve your problem?
