### ISSUE TITLE
Branch for Laravel 5.5

### ISSUE THREAD

**Issue by gustavodebiasi** [jacquestvanzuydam/laravel-firebird#53]
Please, can anybody open a new Branch for the new Laravel 5.5?

I made a fork and made tests with the new version and I already have the pull request for it.

Thank you.

**Comment by jacquestvanzuydam** [comment]
Hi Gustavo,

I have made the branch here: [https://github.com/jacquestvanzuydam/laravel-firebird/tree/5.5-support](https://github.com/jacquestvanzuydam/laravel-firebird/tree/5.5-support)

Thanks for the support.

**Comment by gustavodebiasi** [comment]
Thank you @jacquestvanzuydam, I made a pull request to update the composer.json file ( #54 )
