### ISSUE TITLE
Error "PDOException: could not find driver" only cmd.

### ISSUE THREAD

**Issue by igorfaria6** [jacquestvanzuydam/laravel-firebird#56]
In requests driver works, but all commands dont works (ex: php artisan migrate, vendor/bin/phpunit).

1) BookTest::test_criar_book
PDOException: could not find driver

D:\FONTES\Php\firebird\vendor\jacquestvanzuydam\laravel-firebird\src\Firebird\Connection.php:90
D:\FONTES\Php\firebird\vendor\jacquestvanzuydam\laravel-firebird\src\Firebird\Connection.php:46
D:\FONTES\Php\firebird\vendor\jacquestvanzuydam\laravel-firebird\src\Firebird\ConnectionFactory.php:98
D:\FONTES\Php\firebird\vendor\laravel\framework\src\Illuminate\Database\Connectors\ConnectionFactory.php:64
D:\FONTES\Php\firebird\vendor\laravel\framework\src\Illuminate\Database\Connectors\ConnectionFactory.php:50
D:\FONTES\Php\firebird\vendor\laravel\framework\src\Illuminate\Database\DatabaseManager.php:176
D:\FONTES\Php\firebird\vendor\laravel\framework\src\Illuminate\Database\DatabaseManager.php:68
D:\FONTES\Php\firebird\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php:3351
D:\FONTES\Php\firebird\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php:3317
D:\FONTES\Php\firebird\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php:1861
D:\FONTES\Php\firebird\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php:1834
D:\FONTES\Php\firebird\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php:1450
D:\FONTES\Php\firebird\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php:561
D:\FONTES\Php\firebird\tests\BookTest.php:15

**Comment by KKSzymanowski** [comment]
Just a guess here but maybe do you have different PHP configuration for HTTP requests and CLI.
Is the PDO Firebird extension loaded in CLI?

**Comment by igorfaria6** [comment]
I'm using wampserver. I enabled the firebird driver manually and it worked correctly.

Thanks so much, @KKSzymanowski !
