### ISSUE TITLE
problems whit paginate method

### ISSUE THREAD

**Issue by azamudio1971** [jacquestvanzuydam/laravel-firebird#57]
i'm using support 5.5.
when i want paginate results, laravel return this screens

![clip2net_171127212837](https://user-images.githubusercontent.com/12475479/33301199-108d881c-d3ba-11e7-850e-e18a3e3f8756.png)

![clip2net_171127212813](https://user-images.githubusercontent.com/12475479/33301234-4dd455fc-d3ba-11e7-8778-6ff89d349be8.png)

any idea?

**Comment by azamudio1971** [comment]
searching in google i find this
[https://github.com/laravel/framework/issues/18460](https://github.com/laravel/framework/issues/18460)

How can I solve it without modifying the vendor?

**Comment by KKSzymanowski** [comment]
Extend the firebird driver and modify it then.

**Comment by JJS4ntos** [comment]
I'm with a same problem too.
Have you any news about it?

**Comment by JJS4ntos** [comment]
I got it using the simplePagination function!
Hope it help you.

**Comment by igorfaria6** [comment]
` $users  = User::all();`
`$users = $this->paginate($users)->setPath($request->url());`

paginate function:
` protected function paginate($items, $perPage = 12){`
`        $currentPage = LengthAwarePaginator::resolveCurrentPage();`
`        $currentPageItems = $items->slice(($currentPage - 1) * $perPage, $perPage);`
`        return new LengthAwarePaginator($currentPageItems, count($items), $perPage);`
    `}`


try this

**Comment by mstanarevic** [comment]
Here's my workaround:

Create new file in `App\Database\Query\` named `FirebirdQueryBuilder.php` that has fix in it:

```php
<?php
namespace App\Database\Query;

use Firebird\Query\Builder as BaseBuilder;


class FirebirdQueryBuilder extends BaseBuilder {

	/**
	 * AGGREGATE fix
	 *
	 * Get the count of the total records for the paginator.
	 *
	 * @param  array  $columns
	 * @return int
	 */
	public function getCountForPagination($columns = ['*'])
	{
		$results = $this->runPaginationCountQuery($columns);

		// Once we have run the pagination count query, we will get the resulting count and
		// take into account what type of query it was. When there is a group by we will
		// just return the count of the entire results set since that will be correct.
		if (isset($this->groups)) {
			return count($results);
		} elseif (! isset($results[0])) {
			return 0;
		} elseif (is_object($results[0])) {
			return (int) $results[0]->AGGREGATE;
		} else {
			return (int) array_change_key_case((array) $results[0])['aggregate'];
		}
	}
}
```

Than in your `BaseModel.php` that extends `Firebird\Model` override `newBaseQueryBuilder()` method,
and use new `FirebirdQueryBuilder` that we created:
```php
<?php

namespace App;

use Firebird\Model as Model;
use Illuminate\Http\Request as FormRequest;
use App\Database\Query\FirebirdQueryBuilder as QueryBuilder;

class BaseModel extends Model
{
	/**
	 * Get a new query builder instance for the connection.
	 *
	 * @return \Illuminate\Database\Query\Builder
	 */
	protected function newBaseQueryBuilder()
	{
		$connection = $this->getConnection();

		return new QueryBuilder(
			$connection, $connection->getQueryGrammar(), $connection->getPostProcessor()
		);
	}
}

```

And that's it!
Hope it helps.
Cheers.

**Comment by Rachmat96** [comment]
I still have problem with paginate, Undefined property: stdClass::$aggregate
