### ISSUE TITLE
README on Branch 5.5-Support Shows Information for 5.4-Support

### ISSUE THREAD

**Issue by barricade823** [jacquestvanzuydam/laravel-firebird#65]
5.4-Support - https://github.com/jacquestvanzuydam/laravel-firebird/tree/5.4-support#installation
5.5-Support - https://github.com/jacquestvanzuydam/laravel-firebird/tree/5.5-support#installation

**Comment by jacquestvanzuydam** [comment]
I have amended this. Thank you.
