### ISSUE TITLE
Persitent connection ver 5.4.

### ISSUE THREAD

**Issue by wik1** [jacquestvanzuydam/laravel-firebird#66]
I'm try to use persistent connection an it's doesn't work.
Someone tried

Regards 
Wiesiek

**Comment by fillipenorton** [comment]
Hi 

Did you solve ur problem?

**Comment by wik1** [comment]
Yes.
It's wasn't problem !
If you set up correctly pdo, persistent connection working fine.
But one very important step: after changing to persistent connection or from persistent you have to reboot Apache or Nginx.
After any shut down  database also you shoud reboot Apache or Nginx ... because they  keeping connections to not exist data base. 
If you keeping this rules, everything working fine.
Wiesiek
