### ISSUE TITLE
PDOException: unsupported driver[firebird

### ISSUE THREAD

**Issue by selmo47** [jacquestvanzuydam/laravel-firebird#68]
I had installed this package using:
`composer require jacquestvanzuydam/laravel-firebird:dev-5.5-support`
and i installed also php7.0-interbase tha enables firebird pdo
i enabled pdo-firebird php module with:
`phpenmod pdo_firebird`
when i run : 
`php -m` 
it shows me that pdo_firebird is compiled and loaded.

when i print : 
`print_r(PDO::getavailabledrivers()); `
it shows 

> [0] => 'firebird'

but when i run laravel thinker and try to execute:
`App\EMPLOYEE::all();`

it shows:

> InvalidArgumentException with message: UnsupportedDriver[firebird]'

I'm using php 7 and firebird 2.5 superclassic under ubuntu 16.04 xenial

**Comment by selmo47** [comment]
When tryin to debug, i noticed that laravel continue using its ConnectioFactory (from: vendor
/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php)

how to enforce it to use the factory defined in this package?

**Comment by KKSzymanowski** [comment]
Did you register the service provider?

**Comment by selmo47** [comment]
that was the error; So sorry

I dont know how i forgot this knowing that it was the subject of my contribution in this repo

thanks @KKSzymanowski

**Comment by KKSzymanowski** [comment]
It's always the stupidest thing 😄

**Comment by DJ-Daniel** [comment]
I'm getting the same error but how do I register the service provider?
