### ISSUE TITLE
Problem with lastInsertId

### ISSUE THREAD

**Issue by lnicotra** [jacquestvanzuydam/laravel-firebird#69]
I'm working with the driver in an app that is ok. Now i need to extend this app and my first requirement is to install Laravel Passport package, so i follow every step and when i do "php artisan passport:install" i get the error:
```
In Processor.php line 34:

  SQLSTATE[IM001]: Driver does not support this function: driver does not support lastInsertId()
```
Following the stacktrace i see that the Processor.php file that is using is in vendor\laravel\framework\src\Illuminate\Database\Query\Processors\ and calls lastInsertId php function. I'm stuck in here and don't know what to do to fix this problem.

**Comment by selmo47** [comment]
I think that this fork resolvs this:
[https://github.com/sim1984/laravel-firebird](url)
but, i couldn't neither install it with composer, nor open an isuue on it

**Comment by JuanPSH** [comment]
Try this:

https://github.com/jacquestvanzuydam/laravel-firebird/issues/25#issuecomment-216392037

**Comment by victorvilella** [comment]
If you are using Firebird 1.x it is impossible because there is no support to returing values on insert statements.

Maybe it is impossible because PDO's Firebird support too I suppose.

Anyway, @JuanPSH refereed a alternative solution that I implemented im my project.

**Comment by JoaoOliveiracc** [comment]
My question is which model should I declare public $ incrementing = false?
