### ISSUE TITLE
Support Laravel 5.1.5?

### ISSUE THREAD

**Issue by bernex** [jacquestvanzuydam/laravel-firebird#7]
Does it have support?

Thanks!

**Comment by jacquestvanzuydam** [comment]
I am currently working on this, will hopefully be an update coming soon.

**Comment by jacquestvanzuydam** [comment]
Please use:

``` json
composer require jacquestvanzuydam/laravel-firebird:dev-5.1-support
```

Check the 5.1-support branch for updated Readme
