### ISSUE TITLE
Connect to Firebird DB on non-default port

### ISSUE THREAD

**Issue by mhaubenwallner** [jacquestvanzuydam/laravel-firebird#72]
Hello,

I cannot connect to a Firebird DB that is on a non-default port.
If I connect to the default port (3050) all works fine.

In the [PDO documentation](http://php.net/manual/en/ref.pdo-firebird.connection.php) under example 2 there is the possibility to add a port.
If I change the relevant part (in Connection.php, line 69) I still have the same issue.

Does anyone has a tip for me to get it running?

Thanks and kind regards,
Mario

**Comment by KKSzymanowski** [comment]
I have recently successfully connected to the Firebird DB on a non-default port and here's my configuration:

```
DB_FIREBIRD_HOST=192.168.0.1/3051
DB_FIREBIRD_DATABASE="D:\foo\bar\baz.fdb"
DB_FIREBIRD_USERNAME=user
DB_FIREBIRD_PASSWORD=password
```

```php
'firebird'     => [
    'driver'    => env('DB_FIREBIRD_DRIVER'),
    'host'      => env('DB_FIREBIRD_HOST'),
    'database'  => env('DB_FIREBIRD_DATABASE'),
    'username'  => env('DB_FIREBIRD_USERNAME'),
    'password'  => env('DB_FIREBIRD_PASSWORD'),
    'charset'   => 'ISO-8859-2',
],
```
Maybe that will help you.
