### ISSUE TITLE
Cannot run save method 

### ISSUE THREAD

**Issue by selmo47** [jacquestvanzuydam/laravel-firebird#75]
I create a new Model Object 
`$sale = new Sale();`
Then, i updated its fields 
`$sale->amount=.... # and som other update`

When i tried to insert t with `$sale->save()`
I got the following error:

> SQLSTATE[IM001]: Driver does not support this function: driver does not support lastInsertId()

**Comment by KKSzymanowski** [comment]
Take a look here: https://github.com/jacquestvanzuydam/laravel-firebird/issues/25

**Comment by selmo47** [comment]
yeh, it solves the problem, but for other easen, i need that we can get the last inserted Id
this fork 
[https://github.com/sim1984/laravel-firebird](url)
resolve this, but i cant install it with composer, and i cant also open an issue on it

Any Idea??

**Comment by jacquestvanzuydam** [comment]
I emailed the guys who worked on that fork to issue a pull request back into this repository months ago without any response. As I do not have time for this package at the moment, I will probably come back to it later this year only.
