### ISSUE TITLE
Argument 1 passed to setReconnector() Laravel 5.8.5+

### ISSUE THREAD

**Issue by darkzdiez** [jacquestvanzuydam/laravel-firebird#77]
Hello, I have a problem with the library since the version of laravel 5.8.5 onwards, even probe with a clean installation and gives the same error

Argument 1 passed to Illuminate\Database\Connection::setReconnector() must be callable, null given, called in ...\vendor\laravel\framework\src\Illuminate\Database\DatabaseManager.php on line 179

**Comment by Rachmat96** [comment]
Me too. I have same problem. please help.

**Comment by arbexmb** [comment]
I am having the same problem. Anyone got a sollution?

**Comment by stelsoft** [comment]
For me it was caused by incompatible firebird driver https://packagist.org/packages/jacquestvanzuydam/laravel-firebird

**Comment by jacquestvanzuydam** [comment]
@stelsoft this library is going to be flagged as abandoned, as I haven't had time to work on it since 2016, I'd appreciate if you could tell me which library you are using so I can add it to my readme as an alternative.

**Comment by stelsoft** [comment]
@jacquestvanzuydam This works for me, using laravel 5.8 https://packagist.org/packages/harrygulliford/laravel-firebird

**Comment by jacquestvanzuydam** [comment]
@stelsoft thank you, I will also ask the users to look at forks of this package.

**Comment by KKSzymanowski** [comment]
@jacquestvanzuydam  I kinda reworked your package into my own and made it compatible with Laravel 5.8 and 6.*. I only used it in one project so far and I only read from existing databases, not modyfing schema nor inserting/updating so that part isn't tested at all.

Here's the link: https://github.com/KKSzymanowski/laravel-6-firebird

**Comment by jacquestvanzuydam** [comment]
@KKSzymanowski many thanks :)
