### ISSUE TITLE
Connection reject by remote interface

### ISSUE THREAD

**Issue by fillipenorton** [jacquestvanzuydam/laravel-firebird#78]
Hi! I'm working with the following stack and eventually i have the error: "Connection rejected by remote interface". Sometimes 15 seconds later it back to work

Laravel 5.2
PHP 7.0
Firebird 2.5 classic
Ubuntu 16.04

Thanks for any information

**Comment by rauberJv** [comment]
Hi. 
Have you tried to update firebird?
