### ISSUE TITLE
"Table unkown FOO" but exists

### ISSUE THREAD

**Issue by victorvilella** [jacquestvanzuydam/laravel-firebird#79]
Hi everyone.

I don't know if is a Laravel's bug or a PDO bug. It's annoying me a lot, delaying my deploys and all.

First of all, let me introduce my scenario in production environment. 

* Windows Server 2008 R2
* PHP 5.6 (planning upgrade to 7.3 soon)
* Firebird 1.5 (Doesn't depend on me to upgrade)
* Apache 2.4 

I have a method that does a lot of inserts in 5 different tables (this case I'm processing a e-commerce order). Some of then does only one insert, others many inserts. When I will make a insert on 5th table, my PDO returns SQL error that table does not exist. (**Yeah, It f***** **exists!**)

Even if I change order of inserts, fails always on 5th table. I dunno why and I don't have idea what is going on.

Anyone get a situation like this? My project is a legacy code, not a Laravel project.

**Comment by jacquestvanzuydam** [comment]
@victorvilella Please try one of the forked projects as stated in the Readme.

I never tested this on anything below Firebird 2.5
