### ISSUE TITLE
Eloquent doesnt work correctly

### ISSUE THREAD

**Issue by william-cwb** [jacquestvanzuydam/laravel-firebird#80]
When I do query, i need to do json_decode($model) to access attributes from table.

![image](https://user-images.githubusercontent.com/47876409/125306432-98a19500-e305-11eb-93ba-5c67d595f80e.png)

But, when I do parse, I can't access attributes from Eloquent.

How can I fix this?

**Comment by KKSzymanowski** [comment]
Why do you need to `json_decode`? You can simply access the attributes like object properties:
```php
$customer = TbCliente::find($request['id']);
dump($customer->id);
```

**Comment by jacquestvanzuydam** [comment]
@KKSzymanowski is correct, you shouldn't need to decode the object.

Please try one of the forked projects, as this one is abandoned.
