### ISSUE TITLE
Cant return UTF8 result

### ISSUE THREAD

**Issue by zamarrong** [jacquestvanzuydam/laravel-firebird#9]
I have this erro The Response content must be a string or object implementing __toString(), "boolean" given. when i trying to get data with utf8 charsets like "Almacén"

**Comment by jacquestvanzuydam** [comment]
Have you set the charset in your environment file?

**Comment by zamarrong** [comment]
Yes i have UTF8 in my .env file

2015-07-03 13:40 GMT-06:00 Jacques van Zuydam notifications@github.com:

> Have you set the charset in your environment file?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jacquestvanzuydam/laravel-firebird/issues/9#issuecomment-118412534
> .

## 

Ing. Jorge Zamarrón Gómez.
Consultor en Marketing y Tecnología
www.jorge-zamarron.com

**Comment by jacquestvanzuydam** [comment]
I have tried to replicate this based on the information you have given me. Any chance you can upload some sample code? I was able to store and retrieve data that had UTF8 characters.

**Comment by zamarrong** [comment]
i can give you mi team viewer if you can help me

2015-07-03 14:41 GMT-06:00 Jacques van Zuydam notifications@github.com:

> I have tried to replicate this based on the information you have given me.
> Any chance you can upload some sample code? I was able to store and
> retrieve data that had UTF8 characters.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jacquestvanzuydam/laravel-firebird/issues/9#issuecomment-118422261
> .

## 

Ing. Jorge Zamarrón Gómez.
Consultor en Marketing y Tecnología
www.jorge-zamarron.com

**Comment by jacquestvanzuydam** [comment]
Sorry, I didn't have time for a team viewer session, I would also rather look at some examples of what you're trying?

**Comment by jacquestvanzuydam** [comment]
Pending more feedback, this seems like a non-issue.
